const faq = [
    { ques: "What is Coin Ashoka?", ans: "Coin Ashoka is a crypto investment platform that allows users to earn a fixed 2% interest every month on their invested amount." }
    ,
    { ques: "How much interest can users earn on their investment?", ans: "Users can earn a fixed 2% interest every month on their invested amount. For example, if a user invests 100,000, they will earn 2,000 as interest every month." }
    ,
    { ques: "Is there a lock-in period for the invested amount?", ans: "No, there is no lock-in period for the invested amount. Users can withdraw their invested amount anytime." }
    ,
    { ques: "When can users withdraw the earned interest?", ans: "Users can withdraw the earned interest only after completing 2 years." }
    ,
    { ques: "How can users withdraw their invested amount?", ans: "Users can raise a withdrawal request from the portfolio section of the app. The amount will be transferred within 2 weeks of the request." }
    ,
    { ques: "On which blockchain is Coin Ashoka available?", ans: "Coin Ashoka is available on the Binance Smart Chain (BSC)" },
    {ques:"Is there a management fee for using Coin Ashoka?", ans:"No, there is no management fee for using Coin Ashoka."}
,
{ques:"Are there any transaction fees involved in using Coin Ashoka?", ans:"Yes, there is a transaction fee charged by the payment provider, which is 3% of the invested amount."}
,
{ques:"Why does my investment amount fluctuate on Coin Ashoka?", ans:"The investment amount on Coin Ashoka is fixed in USDT, which is a stablecoin pegged to the value of the US dollar. Therefore, if the value of USDT changes, your investment amount will fluctuate accordingly."}
];




const about = [
    { ques: "",ans:"At Coin Ashoka, we believe that everyone should have access to investment opportunities in the world of cryptocurrency. Our platform is designed to make crypto investments easy, safe, and profitable for all. With a fixed 2% interest rate every month on your invested amount, you can watch your savings grow while taking advantage of the exciting world of cryptocurrency.\n\nWe prioritize the security of your investments and have implemented advanced security measures to ensure that your funds are always safe. Our platform is powered by the Binance Smart Chain (BSC) and we work with trusted payment providers to ensure seamless transactions.\n\nOur user-friendly app is designed to make investing in cryptocurrency accessible to all, even for beginners.\n\nAt Coin Ashoka, we are committed to providing you with a reliable and profitable investment platform that you can trust. Join us today and start investing in the future of finance!"}   
]
const policy = [
    { ques: "USER AGREMENT-VERSION 1-LAST REVISED ON: DECEMBER 25, 2021",
    ans:`
    This user agreement (this “Agreement”) sets forth legally binding terms and conditions your access to and use of any websites, mobile sites, mobile applications, desktop applications, products, or services (the “Services”) offered by CoinAshoka technosoft LLP (“CoinAshoka”)  (to the extent further described below) (“CoinAshoka)”, “us”, “our” and “we”). The “User”, “You”, “Your” shall refer to any natural person or entity and its authorized users that subscribes or uses the Services. Certain features of the Site may be subject to additional guideline, terms, or rules, which will be posted on the Site in connection with such features. All such additional terms, guidelines, and rules are incorporated by reference into this Agreement.
    BY ACCESSING OR USING THE SERVICES, YOU ARE ACCEPTING THIS AGREEMENT (ON BEHALF OF YOURSELF OR THE ENTITY THAT YOU REPRESENT), AND YOU REPRESENT AND WARRANT THAT YOU HAVE THE RIGHT, AUTHORITY, AND CAPACITY TO ENTER INTO THIS AGREEMENT (ON BEHALF OF YOURSELF OR THE ENTITY THAT YOU REPRESENT). YOU MAY NOT ACCESS OR USE THE SERVICES OR ACCEPT THIS AGREEMENT IF YOU ARE NOT AT LEAST 18 YEARS OLD. IF YOU DO NOT AGREE WITH ALL OF THE PROVISIONS OF THIS AGREEMENT, DO NOT ACCESS AND/OR USE THIS SITE.
    THESE TERMS REQUIRE THE USE OF ARBITRATION (SECTION 13.1) ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES RATHER THAN JURY TRIALS OR CLASS ACTIONS ,AND ALSO LIMIT THE REMEDIES AVAILABLE TO YOU IN THE EVENT OF A DISPUTE 
    We may amend this Agreement related to the Services from time to time. Amendments will be effective upon our posting of such updated Agreement at this location or the amended policies or supplemental terms on the applicable Services. Your continued access or use of the Services after such posting constitutes your consent to be bound by the Agreement, as amended.
    YOU ACKNOWLEDGE THAT TRADING IN CRYPTOCURRENCIES INVOLVES A HIGH DEGREE OF RISK. CRYPTOCURRENCIES ARE SUBJECT TO CONSTANT AND FREQUENT FLUCTUATIONS IN VALUE AND EXCHANGE RATES, AND THE VALUE OF YOUR CRYPTOCURRENCY ASSETS MAY INCREASE OR DECREASE AT ANY TIME. ACCORDINGLY, YOU MAY SUFFER A COMPLETE LOSS OF THE FUNDS HELD IN YOUR ACCOUNT. YOU ACKNOWLEDGE THAT YOU ARE SOLELY RESPONSIBLE FOR DETERMINING THE NATURE, SUITABILITY AND APPROPRIATENESS OF THE THESE TRADING RISKS FOR YOU. YOU ACKNOWLEDGE AND AGREE THAT COINASHOKA  BEARS NO RESPONSIBILITY OR LIABILITY TO YOU OR ANY OTHER PERSON WHATSOEVER FOR ANY LOSSES OR GAINS INCURRED IN CONNECTION WITH YOUR USE OF THE SERVICES. YOU ALSO ACKNOWLEDGE AND AGREE THAT COINASHOKA DOES NOT GIVE ADVICE OR RECOMMENDATIONS REGARDING THE TRADING OF CRYPTOCURRENCIES, INCLUDING THE SUITABILITY AND APPROPRIATENESS OF, AND INVESTMENT STRATEGIES FOR, CRYPTOCURRENCIES. 
    YOU ALSO ACKNOWLEDGE AND AGREE THAT COINASHOKA AND YOUR ABILITY TO USE THE SERVICES MAY BE DETRIMENTALLY IMPACTED BY REGULATORY ACTION OR CHANGES IN REGULATIONS APPLICABLE TO CRYPTOCURRENCY. YOU AGREE THAT WE MAY DISCLOSE YOUR PERSONAL AND ACCOUNT INFORMATION IF WE BELIEVE THAT IT IS REASONABLY NECESSARY TO COMPLY WITH A LAW, REGULATION, LEGAL PROCESS, OR GOVERNMENTAL REQUEST.
    YOU HEREBY ACKNOWLEDGE AND AGREE THAT COINASHOKA IS NOT A FINANCIAL INSTITUTION, BANK, CREDIT UNION, TRUST, HEDGE FUND, BROKER OR INVESTMENT OR FINANCIAL ADVISOR, AND IS NOT SUBJECT TO THE SAME LAWS, REGULATIONS, DIRECTIVES OR REQUIREMENT APPLICABLE TO SUCH PERSONS. YOU ACKNOWLEDGE AND AGREE THAT NO ORAL OR WRITTEN INFORMATION OR ADVICE PROVIDED BY COINASHOKA. ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, NOR ANY INFORMATION OBTAINED THROUGH THE SERVICES, WILL OR SHALL CONSTITUTE INVESTMENT, OR FINANCIAL ADVICE, YOU ARE SOLELY AND EXCLUSIVELY RESPONSIBLE FOR ALL TRADING DECISIONS MADE BY YOU WHILE USING THE SERVICES.
    COINASHOKA IS MERELY A TECHNOLOGY PLATFORM AND YOU ARE SOLELY ENTIRELY RESPONSIBLE FOR THE LEGAL, REGULATORY AND TAX COMPLIANCE OF ALL TRANSACTIONS CARRIED OUT BY YOU USING THE SERVICES. 
        •	ACCOUNTS
        •	Account Creation. In order to use certain feature of the Site, you must register for an account (“Account”) and provide certain information about yourself as prompted by the account registration form. You represent and warrant that: (a) all required registration information you submit is truthful and accurate; (b) you will maintain the accuracy of such information; (c) your use of the services is and shall be in accordance with applicable law. You may delete your account at any time, for any reason, by following the instructions on the Site. COINASHOKA may suspend or terminate your Account in accordance with Section 9.
    
    1.2	Identity Verification. You agree to provide us with the information we request for the purpose of identity verification and the detection of money laundering, terrorist financing, fraud, or any other financial crime and permit us to keep a record of such information. You will need to complete certain verification procedures before you are permitted to use the Services and your access to the Services may be altered as a result of information collected on an ongoing basis. The information we request may include certain personal information, including, but not limited to, your name. address, telephone number, e-mail address, date of birth, taxpayer identification number, Government identification number. And information regarding your bank account (such as the name of the bank, the account type, routing number, and account number). In providing us with this or any other information that may be required, you confirm that the information is accurate and authentic. You agree to update this information and keep it current at all times. You authorize us to make the inquiries, whether directly or through third parties, that we consider appropriate, in our sole discretion, to verify your identity or protect you and/or us against fraud or other financial crimes, and to take action we reasonably deem necessary based on the results of such inquiries.
    
    1.3	Certain Restrictions. By using the Services, you represent and warrant that: (i) neither you nor any of your directions, officers, employees, agents, affiliates or representatives is an individual or an entity that is, or is owned or controlled by an individual or entity that is (a) currently the subject of any Sanctions, or (b) located, organized or resident in a Designated Jurisdiction; (ii) you have complied in all material respects with all applicable laws relating to Sanctions, anti-terrorism, anti-corruption and anti-money laundering; and (iii) you have instituted and maintained policies and procedures designed to promote and achieve compliance with such laws. For the purpose of this Agreement, “Designated Jurisdiction” means any country or territory to the extent that such country or territory itself is the subject of any Sanction; “Sanction(s)” means any international economic sanction administered or enforced by the United States Government (including OFAC), the United Nations Security Council, the European Union or other relevant sanctions authority.
    1.4	Account Responsibilities. You are responsible for maintaining the confidentiality of your Account login information and are fully responsible for all activities that occur under your account including all consequences under applicable laws. You agree to immediately notify COINASHOKA of any unauthorized use, or suspected unauthorized use of your Account or any other breach of security. COINASHOKA cannot and will not be liable for any loss or damage arising from your failure to comply with the above requirements.
    
    1.5	Compliance. You are solely responsible for ensuring that your use of the Services is in compliance with all laws and regulations applicable to you and the right to access the Services is automatically revoked where use of the Services is prohibited or to extent that the offering, sale or provision of the Services conflicts with any law, rule or regulation applicable to you.
    1.6	Available Only Where Permitted by Law. The Services are only available in jurisdictions where they may be legally offered for sale. The Services are not available to “U.S. Persons”, as such term is defined under Regulation S promulgated under the Securities Act of 1933. By accessing or using the Site, you represent and warrant that you are not a U.S. Person.
    
    2	ACCESS TO THE SERVICES
        2.1	License. Subject to this Agreement, COINASHOKA grants you a non-transferable, non-exclusive, revocable, limited license to use and access the Services solely for your own personal or internal business purpose, in accordance with the Account type you are currently subscribing to.
    2.2	Modification. COINASHOKA reserves the right, at any time, to modify, suspend, or discontinue the Services (in whole or in part) with or without notice to you. You agree that COINASHOKA will not be liable to you or to any third party for any modification, suspension, or discontinuation of the Services or any part thereof.
    2.3	No Support or Maintenance. You acknowledge and agree that COINASHOKA will have no obligation to provide you with any support or maintenance in connection with the Services.
    2.4	Ownership.	You acknowledge that all the intellectual property rights, including copyrights, patents, trademarks, and trade secrets, in the services and its content are owned by COINASHOKA or its suppliers. Neither this Agreement (nor your access to the Services) transfers to you or any third party any rights, title or interest in or to such intellectual property rights, except for the limited access rights expressly set forth in Section 2.1. COINASHOKA and its suppliers reserve all rights not granted in this Agreement. There are no implied licenses granted under this Agreement.
    2.5	Feedback	If you provide COINASHOKA with any feedback or suggestions regarding the Site (“Feedback”), you hereby assign to COINASHOKA all rights in such Feedback and agree that COINASHOKA shall have the right to use and fully exploit such Feedback and related information in any manner it deems appropriate. COINASHOKA will treat any Feedback you provide to COINASHOKA as non-confidential and non-proprietary. You agree that you will not submit to COINASHOKA any information or ideas that you consider to be confidential or proprietary.
    3.	PROHIBITED ACTIVITIES
        3.1	Prohibited Activities. In connection with your use of Services, you hereby agree that you will not:
            (a) 	violate (or assist any other party in violating) any applicable law, statute, ordinance, or regulation;
            (b) 	intentionally try to defraud (or assist in the defrauding of) COINASHOKA or any other User;
            (c)	provide false, inaccurate, or misleading information;
            (d)	trade taking advantage of any technical glitch, malfunction, failure, delay, default, or security breach;
            (e)	take any action that interferes with, intercepts, or expropriates, any system, data, or information;
            (f) 	partake in any transaction involving the proceeds of illegal activity;
            (g)	attempt to gain unauthorized access to other COINASHOKA Accounts, the Services, or any related networks or system;
            (h)	use the Services on behalf of any third party or otherwise act as an intermediary between COINASHOKA and any third parties;
            (i)	use the Services to engage in conduct that is detrimental to COINASHOKA or to any other User or any other third party;
            (j)	collect any user information from other Users, including, without limitation, email addresses;
            (k)	defame, harass,or violate the privacy or intellectual property rights of COINASHOKA or any other User; or
            (I)	upload, display or transmit any messages, photos, videos or other media that contain illegal goods, pornographic, violent, obscene or copyrighted images or materials for use as an avatar, in connection with a payment or payment request, or otherwise;
            (m) 	In addition, you agree not to: (i) upload, transmit, or distribute to or through the Services any computer viruses, worms, or any software intended to damage or alter a computer system or data; (ii) interfere with, disrupt, or create an undue burden on servers or networks connected to the Services, or violate the regulations, policies or procedures of such networks; (iii) attempt to reserve engineer, de-compile, disable, interfere with, disassemble, copy, or disrupt the integrity or the performance of the Services, any third-party use of the Services, or any third-party data contained therein (except to the extent such restrictions are prohibited by applicable law; or (iv) access the Services in order to build a competitive product or services or copy any ideas, features, functions, or graphics of the Services.
        3.2	Enforcement. We reserve the right (but have no obligation) to investigate and/ or take appropriate action against you in our sole discretion if you engage in Prohibited Activities or violate any other provision of this Agreement or otherwise create liability for us or any other person. Such action may include, in our sole and absolute discretion, terminating your account in accordance with Section 9, reporting you to law enforcement authorities without providing any notice of you about any such report and confiscating any balance in an account which has been terminated.
    4	THIRD-PARTY PRODUCTS AND SERVICES; OTHER USERS
        4.1	Third-Party Services. You acknowledge that the Services will enable or assist you to access, interact with, and/or purchase services from several supported  platform and other third parties via third-party websites or applications (collectively, “Third-Party Services”). Such Third-Party Services are not under the control of COINASHOKA, COINASHOKA, does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third-Party Services and is not responsible for any Third-Party Services. You use all Third-Party Services at your own risk, and should apply a suitable level of caution and discretion in doing so. Any use of Third-party Services is governed solely by the terms and conditions of such Third-Party Services and any contract entered into, or any transaction completed via any Third-party Services, is between you and the relevant third party, and not with COINASHOKA. You shall comply in all respects with all applicable terms of the Third-Party Services that you access or subscribe to in connection with the Services. If at any time any Third-Party Services cease to make their programs available to us on reasonable terms, we may cease to provide such features to you without entitling you to refund, credit, or other compensation.
    4.2	Smart Token Funds; STF Traders. COINASHOKA  allows you to independently connect with STF Traders that offer and manage Smart Token Funds (collectively referred to in these Terms of Use as “STF Traders”). Your interactions with any STF Trader, including any transactions you may enter into with a STF Trader with respect to a Smart Token Fund, are entirely between you and such STF Trader. While COINASHOKA  is meant to facilitate your communication and transactions with other Users and STF Traders, we are not a party to any transaction you may enter into with any other User or STF Trader, including without limitation any offer, purchase or sale of Smart Tokens. Without limitation the foregoing, we are not an agent, representative or promoter with respect to any Smart Token Fund or any STF Trader, and use of the Services by a STF Trader or with respect to a Smart Token Fund does not imply or represent any endorsement by us of such STF Trader or Smart Token Fund. We provide no recommendation or endorsement with regard to any Smart Token Fund listed on the Services, and we are not responsible for the actions or omissions of any STF Trader or other User of the Services.
    4.3	Other Users	We do not guarantee the identity of any User or other party or ensure that a buyer or seller is authorized to complete a transaction or will complete a transaction. Your interactions with other Users are solely between you and such Users. You agree that COINASHOKA will not be responsible for any loss or damage incurred as the result of any such interaction. If there is a dispute between you and any User, we are under no obligation to 
    
    4.4	Release		You hereby release and forever discharge COINASHOKA (and our officers, employees, agents, successors, and assigns) from, and hereby waive and relinquish, each and every past, present and future dispute, claim,controversy,demand,right,obligation,liability,action and cause of action of every kind and nature (including  personal injuries, death, and property damage), that has arisen or arises  directly or indirectly out of, or that relates directly or indirectly to, the Services (including any interactions with, or act or omission of, other Users or any Third-Party Products and Services).
    5.	THE COINASHOKA WALLET
        5.1	Supported Cryptocurrencies. The COINASHOKA  wallet allows you to send, receive and store cryptocurreny (together, “Wallet Transactions”) The COINASHOKA wallet is only available in relation to the cryptocurrencies that COINASHOKA , in its sole discretion, decides to support (“Supported Cryptocurrency” or “Supported Cryptocurrencies”). Information about the Support Cryptocurrencies can be found on the FAQ page on the COINASHOKA website. The Supported Cryptocurrencies may change from time to time. Under no circumstances should you attempt to carry out a COINASHOKA wallet Transaction in relation to a cryptocurrency other than a Supported Cryptocurrency.
    5.2	Transaction instruction. COINASHOKA  will process Wallet Transactions according to your instructions. You accept and agree that COINASHOKA does not;
        (a) 	guarantee the identity of any user, receiver, or other party to a COINASHOKA Wallet Transaction. You are solely responsible for ensuing all transaction details are correct, and you should carefully verify all transactions information prior to submitting transaction instructions to COINASHOKA; or
        (b) 	have any control over, or any liability in relation to, the delivery, quality or any other aspect of any goods or services that you may buy from or sell to any third party. COINASHOKA shall not be responsible for, and will take no action in relation to, ensuring that any buyer or seller you transact with using your COINASHOKA  wallet complete the relevant transaction or has the requisite authority to do so.
        5.3	Receiving cryptocurrency. You may receive Support Cryptocurrency into your COINASHOKA wallet by providing the sender with a receive address generated in your COINASHOKA wallet. Your COINASHOKA wallet will only be credited with Supported Cryptocurrency sent to a receive address generated through your COINASHOKA wallet and associated with that Supported Cryptocurrency. For example your COINASHOKA wallet will be credited with ETH when it is sent to an ETH receive address generated through your COINASHOKA wallet.
        5.4	Fiat Currency P2P transactions. COINASHOKA allows you to use fiat currency funds solely in exchange for certain Supported Cryptocurrencies (like USDT) and with other COINASHOKA Users in so-called “P2P transactions.” IN a P2P transaction, COINASHOKA holds the digital currency in escrow between the two counterparties until payment in fiat currency funds between the buyer and seller Users has been confirmed. Such Supported Cryptocurrency (e.g. USDT) is released as soon as payment is confirmed. COINASHOKA does not take custody or facilitate transfer of the fiat currency funds in this model, and the transfer of the fiat currency funds is solely between Users without any responsibility or liability of COINASHOKA in this connection. Without prejudice to foregoing, you hereby grant COINASHOKA the right to resolve issues and disputes among Users in its sole discretion.
        5.5	Trading between Supported Cryptocurrency. COINASHOKA allows you to trade with other users between various Supported Cryptocurrency (e.g. BTC-ETH,  etc.)
        5.6	Sharing User Information. In the course of processing a Wallet Transactions, COINASHOKA may be required to share your user information with other contractual third parties, or as required under applicable laws or demanded upon a lawful request by any government authority. You hereby irrevocably grant full permission and authority for COINASHOKA to share this information with such contractual third parties, or as required under applicable laws or demanded upon a lawful request by any government authority, and release COINASHOKA from any liability, error, mistake, or negligence related thereto.
        5.7	Trade Corrections. You acknowledge and agree that COINASHOKA may correct, reverse or cancel, in its sole discretion, any order, Trade ,transfer, or other transaction or activity with respect to which COINASHOKA has discovered  that there was an error or abnormality, whether such error or abnormality was caused by you, COINASHOKA or a third party or due to technical issues, system issues, software failure or otherwise. COINASHOKA provides no guarantee or warranty that any such attempt will be successful and will have no responsibility or liability for such error(s) or any correction attempt(s).
    6.	THE CoinAshoka PAIRS (OFFERED AND OPERATED BY COINASHOKA TECHNOSOFT LLP)
    COINASHOKA enables Users to trade with each other in trading pairs and use balances which are denominated notionally in Indian Rupees only for convenience in order to enable Users to calculate the value of the relevant Supported Cryptocurrency being traded (“COINASHOKA Pairs”). Any reference to Indian Rupees or INR on COINASHOKA should not be construed as a reference to Indian Rupees amounting to legal tender (otherwise referred to as ‘fiat currency’ or ‘real money’) unless specifically provided herein.
    Terms applicable to Indian Resident Users for CoinAshoka Pairs
    In non-P2P transactions, Users resident in India (as defined under the Foreign Exchange Management Act, 1999) add to their INR balance by depositing Indian Rupees from their registered account/payment instrument to CoinAshoka’s or its partner’s bank account using regulated banking and payment channels, and can redeem their INR balance to their bank accounts / payment instrument by placing a withdrawal request to coinashoka, upon which request Coinashoka will transfer the INR balance amount to the User’s registered bank account / payment instrument, using regulated banking and payment channels, subject to Know Your Customer and other safeguards carried out in CoinAshoka’s sole discretion, and subject to withdrawal limits published on the website / mobile application from time to time. In this model, CoinAshoka merely acts as a duly appointed agent of the User to whom the payment is due, and does not operate a payment system. You hereby duly appoint CoinAshoka as your agent for this purpose.
    Terms applicable to Non-Indian Resident Users for COINASHOKA Pairs
    In all circumstance, Users not resident in Indian (as defined under the Foreign Exchange Management Act, 1999) (“Foreign Users”) can use limited features of the Services. Foreign Users cannot in any circumstance receive or make payments in Indian Rupees or equivalents on any other fiat currency or equivalents (otherwise referred to as ‘real money’ or ‘fiat currency’). Foreign Users can only use the Services to trade between Supported Cryptocurrencies without any interface to fiat currency. Foreign Users are not entitled to redeem any INR balance with COINASHOKA for Indian Rupees (unlike Users resident in India who may withdraw their INR balance to their bank accounts) or any other fiat currency. The INR balance of a Foreign User is only denoted on the platform for convenience and can only be used by a Foreign User to further trade in Supported Cryptocurrencies. Foreign Users do not therefore carry out any transactions in fiat currency using the Services and merely hold Supported Cryptocurrencies in their COINASHOKA wallets and trade between Supported Cryptocurrencies.
    7.	FEES
        7.1	General. You agree to pay COINASHOKA the fees set forth at https://CoinAshoka.com/fees which may be updated from time to time in our  sole discretion. Any such updated fees will apply prospectively to any trades or other transactions that take place following the effective date of such updated fees. You authorize CoinAshoka to remove any amounts from your Account for any applicable fees owed by you under this Agreement.
    
    
    
    
    
    7.2	Withdrawal / Send fees. 	You may  be charged a fee to send or withdraw a Supported Cryptocurrency from your CoinAshoka Wallet. We currently do not charge fees to deposit or receive Supported Cryptocurrency into your CoinAshoka wallet.
        7.3	Services fees.	CoinAshoka applies a Maker / Taker fee structure for customers who trade Supported Cryptocurrency using the Services. Please consult the page set forth at https://coinashoka.com/fees for further information on applicable Maker and Taker fees. CoinAshoka will, at the time of any transaction on the CoinAshoka Exchange, notify you of any fees that will apply to the transaction. By proceeding with any transaction, you accept and agree to the applicable fees. Such fees will also be displayed in your transaction history upon completion of the transaction.
    8.	CONTESTS.	We may from time to time offer you the ability to participate in contests of skills (“Contest” or “Contests”.  If you choose to participate in any Contests, you accept and agree to be bound and abide by the applicable Contest terms and conditions which will be published on the CoinAshoka website from time to time and incorporated herein by reference (the “Contest Terms”). CoinAshoka reserves the right to modify the Contest Terms or discontinue and contests at any time for any reason, including but not limited to product availability, pricing issues, reduced demand, Prizes, discounts and special pricing may be changed or substituted at any time without prior notice. Taxes on any prize or award are the sole responsibility of the recipient.
    9.	SUSPENSION, TERMINATION, AND CANCELLATION.
        9.1.	General. This Agreement will continue to apply to you terminated by either you or CoinAshoka. Any provision of this Agreement which, either by its terms or give effect to its meaning, must survive, and such other provisions which expressly, or by their nature, are intended to survive termination shall survive the expiration or termination of this Agreement.
    9.1	Suspension, Termination. We may termination your account or suspend your access to the Services at any time with immediate effect for any reason or no reason, in our sole and absolute discretion. We may decline to process any deposit or withdrawal without prior notice and may limit or suspend your use of one or more Services at any time, in our sole discretion. For example, we may, in our sole discretion, delay deposits or withdrawal if we believe the transaction is suspicious, may involves fraud or misconduct, violates applicable laws, or violates the terms of this Agreement. If you have a balance remaining in an Account which has been suspended, we may freeze such balance for so long as the Account is suspended. If the Account is terminated due to fraud, violation of law, or violation of this Agreement, CoinAshoka may, in its discretion, confiscate any balance remaining in the Account and deliver it to any applicable government, law enforcement, or other authorities where circumstances warrant.
    9.3	Cancellation. You may cancel your Account at time by withdrawing all balances and sending us a message through the contact page requesting the cancellation of your Account. Upon termination of this Agreement and your Account, you remain liable for all transactions made while the Account was open.
    10.	DISCLAIMERS
    THE SERVICES ARE PROVIDED ON AN “AS-IS” AND “AS AVAILABLE” BASIS, AND COINASHOKA EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING ALL WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIT ENJOYMENT, ACCURACY, OR NON-INFRINGEMENT. WE (AND OUR SUPPLIERS) MAKE NO WARRANTY THAT THE SERVICES WILL MEET YOUR REQUIREMENTS, WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS, OR WILL BE ACCURATE, RELIABLE, FREE OF VIRUSES OR OTHER HARMFUL CODE, COMPLETE LEGAL, OR SAFE. IF APPLICABLE LAW REQUIRES ANY WARRANTIES WITH RESPECT TO THE SITE, ALL SUCH WARRANTIES ARE LIMITED IN DURATION TO NINETY (90) DAYS FROM THE DATE OF FIRST USE.  COINASHOKA DISCLAIMS ANY AND ALL RESPONSIBILITY OR LIABILITY IN RELATION TO THE CONTENT MADE AVAILABLE THROUGH THE SERVICES, INCLUDING THE CUSTOMER CONTENT, OR ANY CONTENT OR SERVICES PROVIDED BY THIRD PARTIES. COINASHOKA DOES NOT CONTROL OR VET CUSTOMER CONTENT AND IS NOT RESPONSIBLE FOR WHAT USERS POST, TRANSMIT, OR SHARE ON OR THROUGH THE SERVICES. COINASHOKA IS NOT RESPONSIBLE OR LIABLE IN ANY MANNER FOR ANY THIRD-PARTY SERVICES ASSOCIATED WITH OR UTILIZED IN CONNECTION WITH THE SERVICES, INCLUDING THE FAILURE OF ANY SUCH THIRD-PARTY SERVICES OR SUPPORTED PLATFORMS.
    SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU. SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU.
    11.	INDEMNIFICATION.	You agree to indemnify and hold CoinAshoka (and its officers, employees, and agents) harmless, including costs and attorney’s fees. From any claim or demand made by any third party due to or arising out of (a) your use of the Services, (b) your violation of this Agreement, (c) your  violation of applicable laws or regulation, or (d) Third-Party Services. CoinAshoka reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of these claims. You agree not to settle any matter without the prior written consent of CoinAshoka. CoinAshoka will use reasonable efforts to notify you of any such claims, action or proceeding upon becoming aware of it.
    12.	LIMITATION ON LIABILITY  
    TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL COOINASHOKA, ITS AFFILIATES AND THEIR RESPECTIVE SHAREHOLDERS, MEMBERS, DIRECTORS, OFFICERS, EMPLOYEES, ATTORNEYS, AGENTS, REPRESENTATIVES, SUPPLIERS OR CONTRACTORS BE LIABLE FOR ANY INCIDENTAL, INDIRECT, SPECIAL, PUNITIVE, CONSEQUENTIAL OR SIMILAR DAMAGES OR LIABILITIES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF DATA, INFORMATION, REVENUE, PROFIT OR OTHER BUSINESS OR FINANCIAL BENEFIT) ARISING OUT OF OR IN CONNECTION WITH THE SERVICES ANY PERFORMANCE OR NON-PERFORMANCE OF THE SERVICES, OR ANY OTHER PRODUCT, SERVICES OR OTHER ITEM PROVIDED BY OR ON BEHALF OF COINASHOKA AND ITS AFFILIATES WHETHER UNDER CONTRACT, STATUTE, STRICT LIABILITY OR OTHER THEORY EVEN IF COINASHOKA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES EXCEPT TO THE EXTENT OF A FINAL JUDICIAL DETERMINATION THAT SUCH DAMAGES WERE A RESULT OF COINASHOKA GROSS NEGLIGENCE FRAUD, WILLFUL MISCONDUCT OR INTENTIONAL VIOLATION OF LAW. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU.
    NOTWITHSTANDING THE FOREGOING, IN NO EVENT WILL BE LIABILITY OF COINASHOKA, ITS AFFILIATES AND THEIR RESPECTIVE SHAREHOLDERS, MEMBERS, DIRECTORS, OFFICERS, EMPLOYEES,  ATTORNEYS, AGENTS, REPRESENTATIVES, SUPPLIERS OR CONTRACTORS ARISING OUT OF OR IN CONNECTION THE SERVICES, ANY PERFORMANCE OR NON-PERFORMANCE OF THE SERVICES, OR ANY OTHER PRODUCT, SERVICES OR OTHER ITEM PROVIDED BY OR ON BEHALF OF COINASHOKA OR ITS AFFILIATES WHETHER UNDER CONTRACT, STATUTE, STRICT LIABILITY OR OTHER THEORY, EXCEED THE AMOUNT OF THE FEES PAID BY YOU TO COINASHOKA UNDER THIS AGREEMENT IN THE TWELVE-MONTH PERIOD IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM FOR LIABILITY.
    
    
    
    
    
    13.	GENERAL
    
        
        13.2	Applicable Law. The laws of India excluding its choice of law provision, will govern these Terns and any dispute that arises between you and CoinAshoka Technosoft LLP
        13.3	Force Majeure. CoinAshoka is not responsible for damages caused by delay or failure to perform undertakings under this Agreement when the delay or failure is due to fires; strikes; floods; power outages or failures; acts of God or the state’s enemies; lawful acts of public authorities; any and all market movements, shifts, or volatility; computer, server, or internet malfunctions; security breaches or cyber attacks; criminal acts; delays or defaults caused by common carriers; acts or omissions of third parties; or, any other delays, defaults, failures or interruptions that cannot reasonably be foreseen or provided against. In the event of force majeure, CoinAshoka is excused from any and all performance obligations and this Agreement shall be fully and conclusively at an end.
        13.4	Electronic Communications. The communication between you and CoinAshoka use electronic means, whether you use the Site or send us emails, or whether CoinAshoka posts notices on the Site or communicates with you via email. For contractual purpose, you (a) consent to receive communications from CoinAshoka in an electronic form; and (b) agree that all terms and conditions, agreements, notices, disclosures, and other communications that CoinAshoka provides to you electronically satisfy any legal requirement that such communications would satisfy if it were be in a hardcopy writing. The foregoing does not affect your non-waivable rights.
        13.5	Entire Agreement. 	This Agreement, together with CoinAshoka Privacy Policy, constiture the entire agreement between you and us regarding the use of the Services. Our failure to exercise or enforce any right or provision of this Agreement shall not operate as a waiver of such right or provision. The section titles in this Agreement are for convenience only and have no legal or contractual effect. The word “including” means “including without limitation”. If any provision of this Agreement is, for any reason, held to be invalid or unenforceable, the other provisions of this agreement will be unimpaired and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law. Your relationship to CoinAshoka is that of an independent contractor, and neither party is an agent or partner of the other. This Agreement, and your rights and obligations herein, may not be assigned, subcontracted, delegated, or otherwise transferred by you without CoinAshoka prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the forgoing will be null and void. CoinAshoka may freely assign this Agreement. The terms and conditions set forth in this Agreement shall be binding upon assignees.
    
    
    `,}
]


module.exports = { faq, about,policy }